services:
  # Development configuration
  yii2-dev:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
        BUILD_TYPE: dev
      context: .
      dockerfile: ./src/flavor/apache/Dockerfile.apache
    cap_add:
      - NET_BIND_SERVICE
    container_name: yii2-dev
    depends_on:
      - mysql
      - redis
    environment:
      # PHP Core Configuration
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-60}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-100M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-100M}
      # PHP Error Configuration
      PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS:-on}
      # Yii2 Configuration
      YII_DEBUG: ${YII_DEBUG:-true}
      YII_ENV: ${YII_ENV:-dev}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    hostname: yii2-dev
    image: yii2-apache:${PHP_VERSION:-8.4}-debian-dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - yii2-network
    ports:
      - "8080:80"
      - "8443:443"
    profiles: ["dev"]
    user: www-data
    volumes:
      # Application code
      - ./app:/var/www/app
      - ./app/web/assets:/var/www/app/web/assets
      # Composer cache
      - composer_cache:/var/www/.composer
      # NPM cache (for foxy)
      - npm_cache:/var/www/.npm
      # Separate node_modules to avoid host/container conflicts
      - node_modules:/var/www/app/node_modules
      # Vendor directory for faster installs
      - vendor:/var/www/app/vendor
      # Runtime directories
      - ./runtime:/var/www/app/runtime

  # Production configuration
  yii2-prod:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
        BUILD_TYPE: prod
      context: .
      dockerfile: ./src/flavor/apache/Dockerfile.apache
    cap_add:
      - NET_BIND_SERVICE
    container_name: yii2-prod
    depends_on:
      - mysql
      - redis
    environment:
      # PHP Core Configuration
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-30}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-256M}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-50M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-50M}
      # Yii2 Configuration
      YII_DEBUG: false
      YII_ENV: prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    image: yii2-apache:${PHP_VERSION:-8.4}-debian-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - yii2-network
    ports:
      - "8080:80"
      - "8443:443"
    profiles: ["prod"]
    user: www-data
    volumes:
      # Application code
      - ./app:/var/www/app
      - ./app/web/assets:/var/www/app/web/assets
      # Runtime directories
      - ./runtime:/var/www/app/runtime

  # Full testing configuration
  yii2-full:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
        BUILD_TYPE: full
      context: .
      dockerfile: ./src/flavor/apache/Dockerfile.apache
    cap_add:
      - NET_BIND_SERVICE
    container_name: yii2-full
    depends_on:
      - mysql
      - postgres
      - redis
      - mongodb
      - mssql
      - oracle
    environment:
      # PHP Core Configuration
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-120}
      PHP_MEMORY_LIMIT: 1G
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-200M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-200M}
      # Yii2 Configuration
      YII_DEBUG: true
      YII_ENV: test
    image: yii2-apache:${PHP_VERSION:-8.4}-debian-full
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    networks:
      - yii2-network
    profiles: ["full"]
    ports:
      - "8080:80"
      - "8443:443"
    user: www-data
    volumes:
      - ./app:/var/www/app:delegated
      - composer_cache:/var/www/.composer:delegated
      - npm_cache:/var/www/.npm:delegated
      - node_modules:/var/www/app/node_modules:delegated
      - vendor:/var/www/app/vendor:delegated

  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: yii2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: yiitest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - yii2-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # PostgreSQL database
  postgres:
    image: postgres:16
    container_name: yii2-postgres
    environment:
      POSTGRES_DB: yiitest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - yii2-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: yii2-redis
    command: redis-server --appendonly yes
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - yii2-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MongoDB database
  mongodb:
    image: mongo:7
    container_name: yii2-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongopass}
      MONGO_INITDB_DATABASE: yii2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - yii2-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Microsoft SQL Server database
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: yii2-mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_PASSWORD:-YourStr0ng!Passw0rd}
      MSSQL_PID: Developer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - yii2-network
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  # Oracle database
  oracle:
    image: wnameless/oracle-xe-11g-r2:latest
    container_name: yii2-oracle
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - yii2-network
    ports:
      - "1521:1521"
    shm_size: 1g
    volumes:
      - oracle_data:/opt/oracle/oradata

networks:
  yii2-network:
    driver: bridge

volumes:
  composer_cache:
  npm_cache:
  node_modules:
  vendor:
  mysql_data:
  postgres_data:
  redis_data:
  mongodb_data:
  mssql_data:
  oracle_data:
