#!/bin/bash
#==============================================================================
# Apache runtime configuration: ports, defines, SSL certificates and health endpoints
#
# The configuration under /etc/apache2 is static. This step only decides which
# <IfDefine> sections apply and writes them, with the ports and the certificate
# paths, to an environment file sourced by /etc/apache2/envvars (and therefore
# by every apache2ctl invocation, including supervisord restarts and
# docker exec as the container user).
#==============================================================================

readonly APACHE_RUNTIME_ENV_FILE="${YII2_RUN_DIR}/apache/runtime.env"
readonly SSL_GENERATED_DIR="${YII2_RUN_DIR}/ssl"

# Certificate pair chosen by ssl_prepare_certificates
SSL_ACTIVE_CERT_FILE=""
SSL_ACTIVE_KEY_FILE=""

apache_configure() {
    local -a defines=()
    local ssl_dir="${SSL_DIR:-/etc/apache2/ssl}"
    ssl_dir="${ssl_dir%/}"
    local ssl_cert_file="${SSL_CERT_FILE:-${ssl_dir}/cert.pem}"
    local ssl_key_file="${SSL_KEY_FILE:-${ssl_dir}/key.pem}"
    local ssl_chain_file="${SSL_CHAIN_FILE:-}"
    local ssl_auto_generate="${SSL_AUTO_GENERATE:-true}"
    local http_port https_port

    log INFO "Configuring Apache..."

    http_port="$(apache_port APACHE_HTTP_PORT 80)"
    https_port="$(apache_port APACHE_HTTPS_PORT 443)"

    SSL_ACTIVE_CERT_FILE="$ssl_cert_file"
    SSL_ACTIVE_KEY_FILE="$ssl_key_file"

    if [[ "${APACHE_SSL_ENABLED:-true}" != "true" ]]; then
        log INFO "SSL is disabled via APACHE_SSL_ENABLED=false"
    elif [[ "$http_port" == "$https_port" ]]; then
        log ERROR "APACHE_HTTP_PORT and APACHE_HTTPS_PORT are both ${http_port}"
        log WARNING "SSL setup failed, falling back to HTTP-only"
    elif ssl_prepare_certificates "$ssl_dir" "$ssl_cert_file" "$ssl_key_file" "$ssl_auto_generate"; then
        defines+=(SSL_ENABLED)
        if [[ "$https_port" == "443" ]]; then
            defines+=(SSL_DEFAULT_PORT)
        fi

        if [[ "${APACHE_SSL_REDIRECT:-false}" == "true" ]]; then
            log INFO "HTTPS enabled on port ${https_port} with HTTP to HTTPS redirect"
            defines+=(SSL_REDIRECT)
        else
            log INFO "HTTPS enabled on port ${https_port} alongside HTTP on port ${http_port}"
        fi

        if [[ -n "$ssl_chain_file" ]]; then
            if [[ -f "$ssl_chain_file" && -r "$ssl_chain_file" ]]; then
                defines+=(SSL_CHAIN)
            else
                log WARNING "SSL_CHAIN_FILE not found or not readable by $(current_user_label), ignoring: ${ssl_chain_file}"
            fi
        fi

        # OCSP stapling only makes sense for CA-issued certificates
        if [[ "$ssl_auto_generate" == "true" || "${APACHE_DISABLE_OCSP_STAPLING:-false}" == "true" ]]; then
            log INFO "OCSP stapling disabled"
        else
            log INFO "OCSP stapling enabled (external certificates)"
            defines+=(SSL_STAPLING)
        fi
    else
        log WARNING "SSL setup failed, falling back to HTTP-only"
    fi

    if [[ "${ENABLE_HEALTH_ENDPOINT:-true}" == "true" ]]; then
        defines+=(HEALTH_ENDPOINT)
    fi

    if [[ "${ENABLE_FPM_STATUS:-false}" == "true" ]]; then
        defines+=(FPM_STATUS)
    fi

    local arguments="${APACHE_ARGUMENTS:-}"
    local define
    for define in "${defines[@]}"; do
        arguments+=" -D ${define}"
    done

    # The directory belongs to the running user (root-owned in root mode), so no other user can replace the file
    {
        echo "# Generated by the entrypoint at container start. Do not edit."
        apache_env_line APACHE_ARGUMENTS "${arguments# }"
        apache_env_line APACHE_HTTP_PORT "$http_port"
        apache_env_line APACHE_HTTPS_PORT "$https_port"
        apache_env_line HEALTHCHECK_PATH "${HEALTHCHECK_PATH:-/health}"
        apache_env_line SSL_CERT_FILE "$SSL_ACTIVE_CERT_FILE"
        apache_env_line SSL_KEY_FILE "$SSL_ACTIVE_KEY_FILE"
        apache_env_line SSL_CHAIN_FILE "$ssl_chain_file"
    } >"$APACHE_RUNTIME_ENV_FILE"
    chmod 0644 "$APACHE_RUNTIME_ENV_FILE"

    export APACHE_HTTP_PORT="$http_port" APACHE_HTTPS_PORT="$https_port"

    log SUCCESS "Apache configured (defines: ${defines[*]:-none})"
}

# Prints a validated port number from a variable, or exits with an explanation.
# Usage: apache_port <VARIABLE> <default>
apache_port() {
    local value="${!1:-$2}"

    if [[ ! "$value" =~ ^[0-9]{1,5}$ ]] || ((10#$value < 1 || 10#$value > 65535)); then
        log ERROR "$1 must be a port number between 1 and 65535 (got '${value}')"
        exit 1
    fi

    printf '%s' "$((10#$value))"
}

# Exits with an explanation when a non-root user cannot bind the configured ports. Docker allows every port
# (ip_unprivileged_port_start=0); hosts networking, some Kubernetes runtimes and build steps keep the 1024 limit.
apache_check_ports() {
    local start port

    if is_root || [[ ! -r /proc/sys/net/ipv4/ip_unprivileged_port_start ]]; then
        return 0
    fi

    start="$(</proc/sys/net/ipv4/ip_unprivileged_port_start)"
    for port in "$APACHE_HTTP_PORT" "$APACHE_HTTPS_PORT"; do
        if ((port < start)); then
            log ERROR "Port ${port} is privileged here (ip_unprivileged_port_start=${start}) and $(current_user_label) cannot bind it"
            log INFO "Remedy: set APACHE_HTTP_PORT and APACHE_HTTPS_PORT to ports >= ${start} (for example 8080 and 8443)"
            exit 1
        fi
    done
}

# Prints a POSIX shell export line with a single-quoted value.
apache_env_line() {
    local value="${2//\'/\'\\\'\'}"
    printf "export %s='%s'\n" "$1" "$value"
}

# Succeeds when root may load the file as configuration: the file and every directory above it belong to root and are
# not writable by group or others (a sticky directory such as /tmp does not qualify either).
path_trusted_by_root() {
    local path
    path="$(realpath -e -- "$1" 2>/dev/null)" || return 1

    while :; do
        [[ "$(stat -c '%u' -- "$path")" == "0" ]] || return 1
        (($(stat -c '0%a' -- "$path") & 8#022)) && return 1
        [[ "$path" == "/" ]] && return 0
        path="$(dirname -- "$path")"
    done
}

# Uses existing certificates, or generates a self-signed pair in the runtime directory when allowed. Sets
# SSL_ACTIVE_CERT_FILE and SSL_ACTIVE_KEY_FILE. Returns 1 when no usable pair exists.
ssl_prepare_certificates() {
    local ssl_dir="$1"
    local ssl_cert_file="$2"
    local ssl_key_file="$3"
    local ssl_auto_generate="$4"

    if [[ -f "$ssl_cert_file" && -f "$ssl_key_file" ]]; then
        if [[ ! -r "$ssl_cert_file" || ! -r "$ssl_key_file" ]]; then
            log ERROR "SSL certificate or key is not readable by $(current_user_label): ${ssl_cert_file}, ${ssl_key_file}"
            log INFO "Remedy: make both files readable for this user (for example chgrp to its group and chmod 0640), or set APACHE_SSL_ENABLED=false"
            return 1
        fi

        log INFO "Using existing SSL certificates"
        if [[ "${DEBUG_ENTRYPOINT:-false}" == "true" ]]; then
            log DEBUG "Certificate: ${ssl_cert_file} ($(openssl x509 -in "$ssl_cert_file" -subject -enddate -noout 2>/dev/null | tr '\n' ' '))"
            log DEBUG "Private key: ${ssl_key_file}"
        fi
        return 0
    fi

    if [[ "$ssl_auto_generate" != "true" ]]; then
        log WARNING "SSL certificates not found and auto-generation is disabled"
        log INFO "Please mount certificates or set SSL_AUTO_GENERATE=true"
        return 1
    fi

    # An OpenSSL configuration shipped in SSL_DIR wins over the image default; root only loads one that no other user
    # can modify, because an OpenSSL configuration can load arbitrary modules
    local ssl_config="/etc/apache2/ssl/openssl.conf"
    if [[ -f "${ssl_dir}/openssl.conf" && -r "${ssl_dir}/openssl.conf" ]]; then
        if ! is_root || path_trusted_by_root "${ssl_dir}/openssl.conf"; then
            ssl_config="${ssl_dir}/openssl.conf"
        else
            log WARNING "Ignoring ${ssl_dir}/openssl.conf: as root only a file owned by root and not writable by others is loaded"
        fi
    fi

    SSL_ACTIVE_CERT_FILE="${SSL_GENERATED_DIR}/cert.pem"
    SSL_ACTIVE_KEY_FILE="${SSL_GENERATED_DIR}/key.pem"

    log INFO "Generating self-signed SSL certificates for HTTP/2 in ${SSL_GENERATED_DIR}..."
    if ! (umask 077 && openssl req -x509 -newkey rsa:2048 -nodes \
        -keyout "$SSL_ACTIVE_KEY_FILE" -out "$SSL_ACTIVE_CERT_FILE" \
        -days 365 -config "$ssl_config" -extensions v3_req \
        -sha256 >/dev/null 2>&1); then
        log ERROR "Failed to generate SSL certificates"
        rm -f "$SSL_ACTIVE_KEY_FILE" "$SSL_ACTIVE_CERT_FILE"
        return 1
    fi

    chmod 644 "$SSL_ACTIVE_CERT_FILE"
    chmod 600 "$SSL_ACTIVE_KEY_FILE"

    log SUCCESS "Self-signed SSL certificates generated"
    log DEBUG "Certificate: ${SSL_ACTIVE_CERT_FILE}"
    log DEBUG "Private key: ${SSL_ACTIVE_KEY_FILE}"
    return 0
}
