#!/bin/bash
#==============================================================================
# Apache runtime configuration: defines, SSL certificates and health endpoints
#
# The configuration under /etc/apache2 is static. This step only decides which
# <IfDefine> sections apply and writes them, with the certificate paths, to an
# environment file sourced by /etc/apache2/envvars (and therefore by every
# apache2ctl invocation, including supervisord restarts and docker exec).
#==============================================================================

readonly APACHE_RUNTIME_ENV_FILE="/var/run/apache2/runtime.env"

apache_configure() {
    local -a defines=()
    local ssl_dir="${SSL_DIR:-/etc/apache2/ssl}"
    local ssl_cert_file="${SSL_CERT_FILE:-${ssl_dir}/cert.pem}"
    local ssl_key_file="${SSL_KEY_FILE:-${ssl_dir}/key.pem}"
    local ssl_chain_file="${SSL_CHAIN_FILE:-}"
    local ssl_auto_generate="${SSL_AUTO_GENERATE:-true}"

    log INFO "Configuring Apache..."

    if [[ "${APACHE_SSL_ENABLED:-true}" != "true" ]]; then
        log INFO "SSL is disabled via APACHE_SSL_ENABLED=false"
    elif ssl_prepare_certificates "$ssl_dir" "$ssl_cert_file" "$ssl_key_file" "$ssl_auto_generate"; then
        defines+=(SSL_ENABLED)

        if [[ "${APACHE_SSL_REDIRECT:-false}" == "true" ]]; then
            log INFO "HTTPS enabled with HTTP to HTTPS redirect"
            defines+=(SSL_REDIRECT)
        else
            log INFO "HTTPS enabled alongside HTTP"
        fi

        if [[ -n "$ssl_chain_file" ]]; then
            if [[ -f "$ssl_chain_file" ]]; then
                defines+=(SSL_CHAIN)
            else
                log WARNING "SSL_CHAIN_FILE not found, ignoring: ${ssl_chain_file}"
            fi
        fi

        # OCSP stapling only makes sense for CA-issued certificates
        if [[ "$ssl_auto_generate" == "true" || "${APACHE_DISABLE_OCSP_STAPLING:-false}" == "true" ]]; then
            log INFO "OCSP stapling disabled"
        else
            log INFO "OCSP stapling enabled (external certificates)"
            defines+=(SSL_STAPLING)
        fi

        mkdir -p /var/cache/apache2
        chown www-data:www-data /var/cache/apache2
    else
        log WARNING "SSL setup failed, falling back to HTTP-only"
    fi

    if [[ "${ENABLE_HEALTH_ENDPOINT:-true}" == "true" ]]; then
        defines+=(HEALTH_ENDPOINT)
    fi

    if [[ "${ENABLE_FPM_STATUS:-false}" == "true" ]]; then
        defines+=(FPM_STATUS)
    fi

    local arguments="${APACHE_ARGUMENTS:-}"
    local define
    for define in "${defines[@]}"; do
        arguments+=" -D ${define}"
    done

    {
        echo "# Generated by the entrypoint at container start. Do not edit."
        apache_env_line APACHE_ARGUMENTS "${arguments# }"
        apache_env_line HEALTHCHECK_PATH "${HEALTHCHECK_PATH:-/health}"
        apache_env_line SSL_CERT_FILE "$ssl_cert_file"
        apache_env_line SSL_KEY_FILE "$ssl_key_file"
        apache_env_line SSL_CHAIN_FILE "$ssl_chain_file"
    } >"$APACHE_RUNTIME_ENV_FILE"

    log SUCCESS "Apache configured (defines: ${defines[*]:-none})"
}

# Prints a POSIX shell export line with a single-quoted value.
apache_env_line() {
    local value="${2//\'/\'\\\'\'}"
    printf "export %s='%s'\n" "$1" "$value"
}

# Uses existing certificates, or generates a self-signed pair when allowed. Returns 1 when none are usable.
ssl_prepare_certificates() {
    local ssl_dir="$1"
    local ssl_cert_file="$2"
    local ssl_key_file="$3"
    local ssl_auto_generate="$4"

    if [[ -f "$ssl_cert_file" && -f "$ssl_key_file" ]]; then
        log INFO "Using existing SSL certificates"

        if [[ "${DEBUG_ENTRYPOINT:-false}" == "true" ]]; then
            log DEBUG "Certificate: ${ssl_cert_file} ($(openssl x509 -in "$ssl_cert_file" -subject -enddate -noout 2>/dev/null | tr '\n' ' '))"
            log DEBUG "Private key: ${ssl_key_file}"
        fi

        return 0
    fi

    if [[ "$ssl_auto_generate" != "true" ]]; then
        log WARNING "SSL certificates not found and auto-generation is disabled"
        log INFO "Please mount certificates or set SSL_AUTO_GENERATE=true"
        return 1
    fi

    # Prefer an OpenSSL configuration shipped in SSL_DIR, fall back to the image default
    local ssl_config="${ssl_dir}/openssl.conf"
    if [[ ! -f "$ssl_config" ]]; then
        ssl_config="/etc/apache2/ssl/openssl.conf"
    fi

    if [[ ! -d "$ssl_dir" ]]; then
        log INFO "Creating SSL directory: ${ssl_dir}"
        mkdir -p "$ssl_dir"
        chown www-data:www-data "$ssl_dir"
        chmod 755 "$ssl_dir"
    fi

    log INFO "Generating self-signed SSL certificates for HTTP/2..."

    if ! openssl req -x509 -newkey rsa:2048 -nodes \
        -keyout "$ssl_key_file" -out "$ssl_cert_file" \
        -days 365 -config "$ssl_config" -extensions v3_req \
        -sha256 >/dev/null 2>&1; then
        log ERROR "Failed to generate SSL certificates"
        rm -f "$ssl_key_file" "$ssl_cert_file"
        return 1
    fi

    chmod 644 "$ssl_cert_file"
    chmod 600 "$ssl_key_file"
    chown www-data:www-data "$ssl_cert_file" "$ssl_key_file"

    log SUCCESS "Self-signed SSL certificates generated"
    log DEBUG "Certificate: ${ssl_cert_file}"
    log DEBUG "Private key: ${ssl_key_file}"

    return 0
}
